# Generated by Django 3.2.8 on 2021-11-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211028_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Строковый идентификатор (задает пользователь)'),
        ),
    ]
