# Generated by Django 3.2.8 on 2021-11-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_page_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("slug", "author"), name="author_slug_constraint"
            ),
        ),
    ]
