# Generated by Django 3.2.8 on 2021-11-16 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_page_author_slug_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        verbose_name="Строковый идентификатор (задает админ)"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип блока",
                "verbose_name_plural": "Типы блоков",
                "ordering": ("id",),
            },
        ),
    ]
