# Generated by Django 3.2.8 on 2021-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_blocktype"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="label",
            field=models.CharField(
                default="main", max_length=250, verbose_name="Наименование"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blocktype",
            name="slug",
            field=models.SlugField(verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.ManyToManyField(
                related_name="pages",
                through="api.PageBlockRelation",
                to="api.Block",
                verbose_name="Блоки>",
            ),
        ),
    ]
