# Generated by Django 3.2.8 on 2021-11-30 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_auto_20211123_1217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="label",
            field=models.CharField(max_length=35, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                max_length=80,
                null=True,
                verbose_name="Строковый идентификатор (задает пользователь)",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        help_text="Выберите файл",
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        help_text="Выберите файл",
                        null=True,
                        upload_to="avatars/%Y/%m/%d/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Позиция X"
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Позиция Y"
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "border_radius",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Скругление углов"
                    ),
                ),
                (
                    "rotate",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Угол вращения в градусах",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аватар",
                "verbose_name_plural": "Аватарки",
                "ordering": ("id",),
            },
        ),
    ]
