# Generated by Django 3.2.8 on 2021-11-29 09:39

import api.models.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20211129_0853"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatar",
            old_name="author",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="avatar",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
                verbose_name="Файл",
            ),
        ),
    ]
