# Generated by Django 3.2.8 on 2021-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20211201_1435"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatar",
            name="file",
        ),
        migrations.AddField(
            model_name="avatar",
            name="previewFile",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
                verbose_name="Файл для предпросмотра",
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="sourceFile",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
                verbose_name="Исходный Файл",
            ),
        ),
    ]
