# Generated by Django 3.2.8 on 2021-12-03 11:22

import api.models.avatar
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20211201_1746"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="default",
                        unique=True,
                        verbose_name="Код тарифного плана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
                "ordering": ("id",),
            },
        ),
        migrations.AlterField(
            model_name="avatar",
            name="previewFile",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to=api.models.avatar.get_upload_path,
                verbose_name="Файл для предпросмотра",
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="sourceFile",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to=api.models.avatar.get_upload_path,
                verbose_name="Исходный Файл",
            ),
        ),
        migrations.CreateModel(
            name="ButtonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("web", "ссылка"),
                            ("phone", "телефон"),
                            ("email", "емейл"),
                        ],
                        unique=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "pricingPlan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="button_types",
                        to="api.pricingplan",
                        verbose_name="Тарифный план",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип кнопки",
                "verbose_name_plural": "Типы кнопок",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=50, verbose_name="Заголовок"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        max_length=1000, verbose_name="Значение кнопки"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="api.buttontype",
                        verbose_name="Тип кнопки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка (тип блока)",
                "verbose_name_plural": "Кнопка (тип блока)",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="block",
            name="button",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.button",
                verbose_name='Контент блока с типом "button"',
            ),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="pricingPlan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="block_types",
                to="api.pricingplan",
                verbose_name="Тарифный план",
            ),
        ),
    ]
