# Generated by Django 3.2.8 on 2021-12-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20211203_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="api.blocktype",
                verbose_name="Тип блока",
            ),
        ),
    ]
