# Generated by Django 3.2.8 on 2021-12-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_block_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSectionRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Связь страницы с секцией",
                "verbose_name_plural": "Связи страницы с секцией",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SectionBlockRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Связь секции с блоком",
                "verbose_name_plural": "Связи секции с блоком",
                "ordering": ("order",),
            },
        ),
        migrations.RemoveField(
            model_name="block",
            name="section",
        ),
        migrations.RemoveField(
            model_name="page",
            name="blocks",
        ),
        migrations.RemoveField(
            model_name="section",
            name="name",
        ),
        migrations.AddField(
            model_name="section",
            name="background",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цвет фона"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="label",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="blocktype",
            name="slug",
            field=models.SlugField(
                choices=[("text", "text"), ("button", "button")],
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="buttontype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("web", "web"),
                    ("phone", "phone"),
                    ("email", "email"),
                ],
                unique=True,
                verbose_name="Действие",
            ),
        ),
        migrations.DeleteModel(
            name="PageBlockRelation",
        ),
        migrations.AddField(
            model_name="sectionblockrelation",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.block",
                verbose_name="блок",
            ),
        ),
        migrations.AddField(
            model_name="sectionblockrelation",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.section",
                verbose_name="секция",
            ),
        ),
        migrations.AddField(
            model_name="pagesectionrelation",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.page",
                verbose_name="страница",
            ),
        ),
        migrations.AddField(
            model_name="pagesectionrelation",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.section",
                verbose_name="секция",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="sections",
            field=models.ManyToManyField(
                related_name="pages",
                through="api.PageSectionRelation",
                to="api.Section",
                verbose_name="Секции",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="blocks",
            field=models.ManyToManyField(
                related_name="sections",
                through="api.SectionBlockRelation",
                to="api.Block",
                verbose_name="Блоки",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionblockrelation",
            constraint=models.UniqueConstraint(
                fields=("section", "block"), name="section_block_relation"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesectionrelation",
            constraint=models.UniqueConstraint(
                fields=("section", "page"), name="page_section_relation"
            ),
        ),
    ]
