# Generated by Django 3.2.8 on 2021-12-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0016_auto_20211204_0837"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Цвет фона",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Контент Блока] Секция",
                "verbose_name_plural": "[Контент Блока] Секция",
                "ordering": ("id",),
            },
        ),
        migrations.AlterModelOptions(
            name="button",
            options={
                "ordering": ("id",),
                "verbose_name": "[Контент Блока] Кнопка",
                "verbose_name_plural": "[Контент Блока] Кнопка",
            },
        ),
        migrations.AlterModelOptions(
            name="text",
            options={
                "ordering": ("id",),
                "verbose_name": "[Контент Блока] Текст",
                "verbose_name_plural": "[Контент Блока] Текст",
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="blocks",
            field=models.ManyToManyField(
                related_name="pages",
                through="api.PageBlockRelation",
                to="api.Block",
                verbose_name="Блоки",
            ),
        ),
        migrations.CreateModel(
            name="SectionBlockRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.block",
                        verbose_name="блок",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.section",
                        verbose_name="секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь блока с секцией",
                "verbose_name_plural": "Связи блоков с секцией",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="section",
            name="blocks",
            field=models.ManyToManyField(
                related_name="sections",
                through="api.SectionBlockRelation",
                to="api.Block",
                verbose_name="Блоки",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.section",
                verbose_name='Контент блока с типом "section"',
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionblockrelation",
            constraint=models.UniqueConstraint(
                fields=("block", "section"), name="section_block_relation"
            ),
        ),
    ]
