# Generated by Django 3.2.8 on 2021-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20211204_0919"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="author",
        ),
        migrations.AlterField(
            model_name="blocktype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("text", "text"),
                    ("button", "button"),
                    ("section", "section"),
                ],
                verbose_name="slug",
            ),
        ),
    ]
