# Generated by Django 3.2.8 on 2021-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20211204_0932"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktype",
            name="in_list",
            field=models.BooleanField(
                default=True,
                verbose_name="Получать этот тип при запросе списка типов",
            ),
        ),
    ]
