# Generated by Django 3.2.8 on 2021-12-05 08:36

import api.models.types.section
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_blocktype_in_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="backgroundFile",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to=api.models.types.section.get_upload_path,
                verbose_name="Исходный Файл",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="borderRadius",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Скругление углов",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="paddingBottom",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Отступ снизу",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="paddingLeft",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Отступ слева",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="paddingRight",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Отступ справа",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="paddingTop",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Отступ сверху",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="button",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block",
                to="api.button",
                verbose_name='Контент блока с типом "button"',
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="section",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block",
                to="api.section",
                verbose_name='Контент блока с типом "section"',
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="text",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block",
                to="api.text",
                verbose_name='Контент блока с типом "text"',
            ),
        ),
    ]
