# Generated by Django 3.2.8 on 2021-12-07 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0020_auto_20211205_0836"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="label",
                        max_length=255,
                        null=True,
                        verbose_name="Наименование темы",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Код темы",
                    ),
                ),
                (
                    "background_primary",
                    models.CharField(
                        blank=True,
                        default="white",
                        max_length=255,
                        null=True,
                        verbose_name="Цвет фона основной",
                    ),
                ),
                (
                    "background_secondary",
                    models.CharField(
                        blank=True,
                        default="white",
                        max_length=255,
                        null=True,
                        verbose_name="Цвет фона второстепенный",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="black",
                        max_length=255,
                        null=True,
                        verbose_name="Цвет текста",
                    ),
                ),
                (
                    "headerColor",
                    models.CharField(
                        blank=True,
                        default="black",
                        max_length=255,
                        null=True,
                        verbose_name="Цвет заголовков",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
            },
        ),
    ]
