# Generated by Django 3.2.8 on 2021-12-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        max_length=50, verbose_name="Размер аватарки"
                    ),
                ),
            ],
            options={
                "verbose_name": "[Контент Блока] Аватар",
                "verbose_name_plural": "[Контент Блока] Аватар",
                "ordering": ("id",),
            },
        ),
        migrations.AlterField(
            model_name="blocktype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("text", "text"),
                    ("button", "button"),
                    ("section", "section"),
                    ("avatar", "avatar"),
                ],
                verbose_name="slug",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="avatar",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block",
                to="api.avatarblock",
                verbose_name='Контент блока с типом "avatar"',
            ),
        ),
    ]
