# Generated by Django 3.2.8 on 2021-12-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_auto_20211209_1014"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Контент Блока] Список",
                "verbose_name_plural": "[Контент Блока] Список",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ListItemBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Контент Блока] Список (элемент списка)",
                "verbose_name_plural": "[Контент Блока] Список (элемент списка)",
                "ordering": ("id",),
            },
        ),
        migrations.AlterField(
            model_name="blocktype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("text", "text"),
                    ("button", "button"),
                    ("section", "section"),
                    ("avatar", "avatar"),
                    ("list", "list"),
                ],
                verbose_name="slug",
            ),
        ),
        migrations.CreateModel(
            name="ListItemBlockRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.listitemblock",
                        verbose_name="Элемент",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.listblock",
                        verbose_name="Список",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь списка с элементом (тип блока Список)",
                "verbose_name_plural": "Связи списков с элементами (тип блока Список)",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="listblock",
            name="items",
            field=models.ManyToManyField(
                related_name="lists",
                through="api.ListItemBlockRelation",
                to="api.ListItemBlock",
                verbose_name="Элементы",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="list",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block",
                to="api.listblock",
                verbose_name='Контент блока с типом "list"',
            ),
        ),
        migrations.AddConstraint(
            model_name="listitemblockrelation",
            constraint=models.UniqueConstraint(
                fields=("item", "list"), name="list_item_block_relation"
            ),
        ),
    ]
