# Generated by Django 3.2.8 on 2021-12-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_auto_20211210_0801"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listblock",
            name="block",
        ),
        migrations.AddField(
            model_name="block",
            name="list",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block",
                to="api.listblock",
                verbose_name='Контент блока с типом "list"',
            ),
        ),
    ]
