# Generated by Django 3.2.8 on 2021-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20211210_0813"),
    ]

    operations = [
        migrations.AddField(
            model_name="listblock",
            name="fontSize",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Размер текста",
            ),
        ),
        migrations.AddField(
            model_name="listblock",
            name="template",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Шаблон"
            ),
        ),
    ]
