# Generated by Django 3.2.8 on 2021-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_auto_20211210_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="listblock",
            name="iconSize",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Размер иконки",
            ),
        ),
    ]
