# Generated by Django 3.2.8 on 2021-12-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_listblock_iconsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="block_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="api.blocktype",
                verbose_name="Тип блока для которого предназначена картинка",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="common",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Общая картинка",
            ),
        ),
    ]
