# Generated by Django 3.2.8 on 2021-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_button_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=35, verbose_name="Наименование"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=80,
                        null=True,
                        verbose_name="Строковый идентификатор",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="image",
            old_name="common",
            new_name="is_common",
        ),
        migrations.AlterField(
            model_name="buttontype",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Действие"),
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                related_name="images", to="api.ImageTag", verbose_name="Теги"
            ),
        ),
    ]
