# Generated by Django 3.2.8 on 2021-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_auto_20211215_0658"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="block_type",
        ),
        migrations.AddField(
            model_name="image",
            name="block_types",
            field=models.ManyToManyField(
                related_name="images",
                to="api.BlockType",
                verbose_name="Типы блоков для которых предназначена картинка",
            ),
        ),
    ]
