# Generated by Django 3.2.8 on 2021-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_auto_20211215_0804"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagetag",
            options={
                "ordering": ("id",),
                "verbose_name": "Тег для поиска картинок",
                "verbose_name_plural": "Теги для поиска картинок",
            },
        ),
        migrations.AlterField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="images",
                to="api.ImageTag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="imagetag",
            name="slug",
            field=models.SlugField(
                default="default",
                max_length=80,
                verbose_name="Строковый идентификатор",
            ),
            preserve_default=False,
        ),
    ]
