# Generated by Django 3.2.8 on 2021-12-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_auto_20211215_0828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktype",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("text", "text"),
                    ("button", "button"),
                    ("section", "section"),
                    ("avatar", "avatar"),
                    ("list", "list"),
                ],
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
