# Generated by Django 3.2.8 on 2021-12-16 11:49

import api.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_blocktype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="borderRadius",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Скругление углов"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="previewFile",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to=api.models.image.get_upload_path,
                verbose_name="Файл для предпросмотра",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="rotate",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Угол вращения в градусах"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="scale",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Увеличение"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="x",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Позиция X"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="y",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Позиция Y"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="Выберите файл",
                null=True,
                upload_to=api.models.image.get_upload_path,
                verbose_name="Файл",
            ),
        ),
    ]
