# Generated by Django 3.2.8 on 2021-12-20 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_auto_20211217_0931"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagetag",
            options={
                "ordering": ("id",),
                "verbose_name": "Тег для картинок",
                "verbose_name_plural": "Теги для картинок",
            },
        ),
        migrations.RemoveField(
            model_name="imagetag",
            name="label",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="background_primary",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="background_secondary",
        ),
        migrations.AddField(
            model_name="buttontype",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buttons",
                to="api.image",
                verbose_name="Иконка",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="search",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Список слов для поиска картинки",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="background",
            field=models.CharField(
                blank=True,
                default="white",
                max_length=255,
                null=True,
                verbose_name="Цвет фона",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="backgroundImage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="themes",
                to="api.image",
                verbose_name="Картинка фона",
            ),
        ),
        migrations.AlterField(
            model_name="imagetag",
            name="slug",
            field=models.SlugField(max_length=80, verbose_name="Слаг тега"),
        ),
    ]
