# Generated by Django 3.2.8 on 2021-12-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_auto_20211220_1644"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="label",
            field=models.CharField(
                blank=True,
                default="my_theme",
                max_length=255,
                null=True,
                verbose_name="Наименование темы",
            ),
        ),
        migrations.CreateModel(
            name="ThemeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        max_length=255,
                        unique=True,
                        verbose_name="Слаг типа темы",
                    ),
                ),
                (
                    "pricingPlan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_types",
                        to="api.pricingplan",
                        verbose_name="Тарифный план",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="theme",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="themes",
                to="api.themetype",
                verbose_name="Тип",
            ),
        ),
    ]
