# Generated by Django 3.2.8 on 2021-12-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_auto_20211222_0814"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="themetype",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Тип тем",
                "verbose_name_plural": "Типы тем",
            },
        ),
        migrations.AddField(
            model_name="themetype",
            name="order",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Позиция в сортировке списка"
            ),
        ),
    ]
