# Generated by Django 3.2.8 on 2021-12-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_auto_20211224_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="button",
            name="backgroundColor",
            field=models.CharField(
                blank=True,
                default="#0000FF",
                max_length=255,
                null=True,
                verbose_name="Цвет фона",
            ),
        ),
        migrations.AddField(
            model_name="button",
            name="backgroundGradient",
            field=models.CharField(
                blank=True,
                default="linear-gradient(to right, #FFFFFF, #FFFFFF)",
                max_length=255,
                null=True,
                verbose_name="Градиент фона",
            ),
        ),
        migrations.AddField(
            model_name="button",
            name="backgroundType",
            field=models.CharField(
                blank=True,
                default="color",
                max_length=255,
                null=True,
                verbose_name="Тип фона",
            ),
        ),
        migrations.AddField(
            model_name="button",
            name="color",
            field=models.CharField(
                blank=True,
                default="#000000",
                max_length=255,
                null=True,
                verbose_name="Цвет текста",
            ),
        ),
    ]
