# Generated by Django 3.2.8 on 2021-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_auto_20211228_0953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="button",
            name="backgroundGradient",
        ),
        migrations.RemoveField(
            model_name="button",
            name="backgroundType",
        ),
        migrations.AddField(
            model_name="section",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Цвет текста",
            ),
        ),
    ]
