# Generated by Django 3.2.8 on 2021-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_auto_20211228_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="backgroundPosition",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Позиция фонового изображения",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="backgroundSize",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Размер фонового изображения",
            ),
        ),
    ]
