# Generated by Django 3.2.8 on 2021-12-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_auto_20211228_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="backgroundPosition",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Позиция фонового изображения",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="backgroundSize",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Размер фонового изображения",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="backgroundRepeat",
            field=models.CharField(
                blank=True,
                default="no-repeat",
                max_length=255,
                null=True,
                verbose_name="Зацикливать изображение",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="backgroundRepeat",
            field=models.CharField(
                blank=True,
                default="no-repeat",
                max_length=255,
                null=True,
                verbose_name="Зацикливать изображение",
            ),
        ),
    ]
