# Generated by Django 3.2.8 on 2021-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_auto_20211229_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="ratio",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Соотношение сторон у preview (width/height)",
            ),
        ),
    ]
