# Generated by Django 3.2.8 on 2021-12-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_image_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="ratio",
        ),
        migrations.AddField(
            model_name="image",
            name="borderX",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Горизонтальный бордер для редактора",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="borderY",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Вертикальный бордер для редактора",
            ),
        ),
    ]
