# Generated by Django 3.2.8 on 2022-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_auto_20211230_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="animation",
            field=models.FileField(
                blank=True,
                help_text="Выберите файл анимации",
                null=True,
                upload_to="themes/animations/",
                verbose_name="Анимация",
            ),
        ),
    ]
