# Generated by Django 3.2.8 on 2022-02-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_theme_animationfixed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="animationFixed",
        ),
        migrations.AddField(
            model_name="theme",
            name="animationPosition",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Позиция анимации",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="animationSize",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Размер анимации",
            ),
        ),
    ]
