# Generated by Django 3.2.8 on 2022-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_auto_20220207_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="animationPreserveAspectRatioScale",
            field=models.CharField(
                blank=True,
                default="slice",
                max_length=255,
                null=True,
                verbose_name="Масштаб анимации",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="animationPreserveAspectRatioX",
            field=models.CharField(
                blank=True,
                default="Min",
                max_length=255,
                null=True,
                verbose_name="Выравнивание анимации по X",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="animationPreserveAspectRatioY",
            field=models.CharField(
                blank=True,
                default="Min",
                max_length=255,
                null=True,
                verbose_name="Выравнивание анимации по Y",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="animationPosition",
            field=models.CharField(
                blank=True,
                default="top",
                max_length=255,
                null=True,
                verbose_name="Позиция обертки анимации",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="animationSize",
            field=models.CharField(
                blank=True,
                default="width",
                max_length=255,
                null=True,
                verbose_name="Размер обертки анимации",
            ),
        ),
    ]
