# Generated by Django 3.2.8 on 2022-05-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_auto_20220427_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="collapsedlistblock",
            name="fontSize",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Размер текста",
            ),
        ),
    ]
