# Generated by Django 3.2.8 on 2021-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211103_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
