# Generated by Django 3.2.8 on 2021-12-22 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_auto_20211222_0827"),
        ("users", "0005_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.theme",
                verbose_name="Тема",
            ),
        ),
    ]
