# Generated by Django 3.2.8 on 2022-05-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_auto_20220515_1231"),
        ("users", "0006_customuser_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="index_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="index_users",
                to="api.page",
                verbose_name="Индексная страница",
            ),
        ),
    ]
